import streamlit as st

st.sidebar.markdown("<h4>Milk Mocha Sayfasına Hoş Geldin!</h4>", unsafe_allow_html=True)
st.sidebar.image("resimler/happy.gif")
tab1, tab2, tab3 = st.tabs(["Welcome","Memories", "Son Durak"])

with tab1:
    st.subheader("Hoş geldin! Burada olduğun için mutluyum :)")
    st.image("resimler/milkmocha-milkmochaalex.gif")
    st.subheader("Siteye göz gezdirmek için pencereleri sırasıyla tıklaman gerekiyor. Hazırsan birlikte kısa bir tura çıkıyoruz.")
    st.subheader("İyi yolculuklar :)")
    st.divider()
    st.subheader("-Mocha ")

with tab2:
    st.subheader("Anılar durağına hoş geldin.")
    st.subheader("Aşağıya kaydırarak ilerleyebilirsin :)")
    st.divider()
    st.divider()
    st.markdown("_İlk anıya ilk atılan görselle başlayalım. Milk'in Mocha'ya gönderdiği o ilk resim:_")
    st.image(image="resimler/anılarımız/ilk_anı.jpg",width=300)
    st.markdown("_Açıkçası ilk atılan resim olduğu için hala saklıyorum ve yeri bende ayrı :)_")
    st.divider()
    st.divider()
    st.markdown("_Yine ilklerden devam ediyoruz ve bu da Mocha'nın ilk attığı ve Milk'in de beğendiği o şarkı: 'Merhabalar'_")
    st.image(image="resimler/anılarımız/hayaller/merhabalar.jpg",width=300)
    st.divider()
    st.divider()
    st.markdown("_Şimdiki görselde ise Mocha'nın Milk'e ilk hediyesini görmekteyiz._")
    st.image(image="resimler/ilk hediyeler/ilk hediyeler.jpg")
    st.markdown("_Kalemlerini sürekli kaybettiğini söyleyince aklıma bu fikir gelmişti._")
    st.divider()
    st.divider()
    st.markdown("_Sıradaki görseller ise Discord üzerinden yaptığımız buluşmalardan geliyor:_ ")
    st.image(image="resimler/anılarımız/dc.jpg",width=300) 
    st.image(image="resimler/anılarımız/dc11.jpg",width=300) 
    st.image(image="resimler/anılarımız/WhatsApp Görsel 2024-06-20 saat 14.56.38_919b4838.jpg",width=300) 
    st.markdown("_Poker geceleri de fena değildi sanki :)_")
    st.divider()
    st.divider()
    st.markdown("_Şimdiki resim ise ikimizin de çok sevdiği, ilk gördüğümüz andan itibaren içimizde yumoşlar oluşturan bir görsel..._")
    st.image(image="resimler/anılarımız/hayaller/hayaller.jpg",width=300) 
    st.markdown("_Resme dikkatli bakıldığında küçük bir Ebru ayakkabıları görmektesiniz._") 
    st.markdown("_Tabii ısırma isteği de ardından gelmekte_")    
    st.divider()
    st.divider()
    st.markdown("_Sıradaki anı görseli, eniştenle çekildiğiniz o dudak pozunu yıllar sonra benim için tekrardan çekilmeniz:_")
    st.image(image="resimler/anılarımız/komik anlar/komik an.jpg",width=300) 
    st.markdown("_Bunu anı kısmına koydum evet.. :(_")
    st.divider()
    st.divider()
    st.markdown("_Şimdiki görseller yapay zekaya bizi çizdirdiğin resimlerden:_")
    st.image(image="resimler/anılarımız/hayaller/WhatsApp Görsel 2024-06-20 saat 19.18.47_5e0e86bf.jpg",width=300) 
    st.image(image="resimler/anılarımız/hayaller/WhatsApp Görsel 2024-06-20 saat 19.18.50_752096c4.jpg",width=300) 
    st.markdown("_Her ne kadar çizdirirken bizi deli etse de verilen çıktılar arasında en iyileri buydu :)_")
    st.divider()
    st.divider()
    st.markdown("_Sırada Hayday durağı geliyor :) Hayday oynadığımız sıra seni düşünerek yaptığım çiftliğimdeki küçük bir alan:_")
    st.image(image="resimler/ilk hediyeler/ilkler.jpg")     
    st.divider()
    st.divider()
    st.markdown("_Şimdiki görsel Mocha'nın hediye ettiği o dört yapraklı şans yoncası kolyesi.._")
    st.image(image="resimler/ilk hediyeler/ilk hediyele.jpg",width=300)     
    st.markdown("_Sonrasında bir daha bulamasak da o zamana kadar hep boynundan çıkarmadığın için teşekkür ederim._")
    st.divider()
    st.divider()
    st.markdown("_Burada biraz meraklı olan İrem ile uğraşıyoruz :)_")
    st.image(image="resimler/anılarımız/komik anlar/komik anlarr.jpg",width=300)
    st.divider()
    st.divider()
    st.markdown("_Benim yalnız kaldığımda sana yazdığım o şiir:_")    
    st.image(image="resimler/anılarımız/WhatsApp Görsel 2024-06-20 saat 15.02.52_9e70ac4e.jpg",width=300)
    st.divider()
    st.divider()   
    st.markdown("_Şimdi biraz başa gideceğiz. İlk etkilendiğimiz sohbetten bazı ss'ler:_")
    st.markdown("_Not: Okuma sırası her görsel için aşağıdan yukarıya doğru olmalı._")
    st.image(image="resimler/anılarımız/yeşil.jpg")
    st.image(image="resimler/anılarımız/yeşil2.jpg")
    st.image(image="resimler/anılarımız/yeşil3.jpg")
    st.divider()
    st.divider()
    st.markdown("_O meşhur dudak hareketimiz ve ben:_")
    st.image(image="resimler/anılarımız/WhatsApp Görsel 2024-06-20 saat 14.56.38_3ec0aa3d.jpg",width=300)
    st.image(image="resimler/anılarımız/WhatsApp Görsel 2024-06-20 saat 14.56.38_c1f48ae9.jpg",width=300)
    st.image(image="resimler/mochadan görseller/bendennnnn.jpg",width=300)
    st.markdown("_Sondakinde dil de eklenmiş ama neyse :P_")
    st.divider()
    st.divider()
    st.markdown("_Aramızda anısı olan bazı resimler:_")
    st.image(image="resimler/anılarımız/hayaller/hayallerrr.jpg",width=300)
    st.image(image="resimler/anılarımız/hayaller/hayalle.jpg",width=300)
    st.image(image="resimler/anılarımız/hayaller/WhatsApp Görsel 2024-06-20 saat 14.56.38_2cb0f824.jpg",width=300)
    st.divider()
    st.divider() 
    st.markdown("_Aramızda anısı olan şarkımız:_")
    st.image(image="resimler/anılarımız/hayaller/WhatsApp Görsel 2024-06-20 saat 19.20.08_364afe3e.jpg",width=300)
    st.divider()
    st.divider()  
    st.markdown("_Şimdi de hediye duraklarını tamamlayalım:_")
    st.image(image="resimler/ilk hediyeler/ilk hediyee.jpg", width=400)
    st.markdown("_Doğum günlerinde özellikle daha çok düşünürdüm. Çünkü uzak mesafenin getirdiği zorluklardan birisi de sevdiğinin insanın özel gününde fiziksel olarak bir arada olamamak.. Bunu kapatabilmek için hep elimden geleninden fazlasını yapmaya çalıştım._")
    st.divider()  
    st.markdown("_Fakat bir hediye beni hayal kırıklığına uğratmıştır diyecek olursam o da budur..._")
    st.image(image="resimler/ilk hediyeler/ilk hediyeler hayal kırıklığı.jpg",width=400)
    st.markdown("_Gemi yerine surf yapan insan mı??? Neyseki anlayışlı bir Milk ile beraberdim. Thanks God!_")
    st.divider()  
    st.divider()
    st.markdown("_Milk'in gönderdiği ve beni çok etkileyen anlamlı hediye:_")  
    st.image(image="resimler/anılarımız/WhatsApp Görsel 2024-06-20 saat 15.02.53_c945ef0f.jpg",width=300)
    st.markdown("_Not: Hala daha zarfla birlikte cüzdanımın içinde duruyorlar._")  
    st.divider()  
    st.divider()
    st.markdown("_Düzenli olarak yaptığımız Kinder sürpriz yumurta anılarımız:_")
    st.image(image="resimler/anılarımız/komik anlar/kinder.jpg",width=300)
    st.image(image="resimler/anılarımız/komik anlar/biz.jpg",width=300)
    st.markdown("_Bazen halen daha senin adına seçip alıyorum. Belki bir gün yeniden sen seçmeye başlarsın_")
    st.divider()  
    st.divider()
    st.markdown("_Senin bana son doğum günümde hazırladığın sunum:_")
    st.image(image="resimler/anılarımız/Resim1.png")
    st.image(image="resimler/anılarımız/Resim2.png")
    st.markdown("_Burada Milk'in sevgisinden bahsederken yıldızlar örneğini vermiştin._")
    st.markdown("_O kadar güzel ve duygusaldı ki.. Her daim yanımda olduğunu hissettirirdin bana. İyi ve kötü zamanlarda asla yalnız olmadığımı öğrettin. Bu bana her şeyi başarabileceğimin gücünü verirdi._")
    st.markdown("**Ve ben artık o gücümü kaybettim.**")
    st.divider()  
    st.divider()
    st.markdown("**Anılar durağının şimdilik sonu. Diğer durağa uğramak için lütfen en üstteki 'Son Durak' sekmesine tıkla.**")
    
    
with tab3:
    
    if 'disable_second_button' not in st.session_state:
        st.session_state.disable_second_button = False

    st.markdown("_Bu durağa kadar geldiysen teşekkür ederim. Anılar kısmında elbette yaşanılan bütün anılar yok. Sadece küçük bir fragman diyebiliriz. Geçirilen her an özel her an tarifsiz duygu içeriyor. Dönüp bu zamanlara baktığımızda her şey çok kısa gibi, ama koca iki sene._")
    st.markdown("_Şimdi yapman gereken iki seçenek mevcut aşağıda. İlk seçenek tıklandığında var olan tüm anılar ve duyguları silecek. Sonrasında hiçbir şey olmayacak ve ikinci seçeneğe asla tıklanamayacak. Eğer ikinci seçeneği seçersen anılar silinmeyecek ve yeni bir pencere açılacak. Bu pencerede neler çıkacağını bu noktada bilemiyoruz. Yalnızca açıldığında görebileceksin. O yüzden kararını düşünerek vermelisin. Tıpkı şu an yaşadığımız hayat gibi bu da bir seçim. Kararlarımız bir sonraki adımların belirsizliğiyle devam eder. Onları açmadan nelerle karşılaşacağımızı bilemeyiz. Her neyi seçecek olursan seninle tanışmak benim başıma gelen en güzel şeydi Milk!_")

    st.divider()
    if st.button("**Tüm Anı ve Duyguları Sil**"):
        st.session_state.disable_second_button = True
        st.error("ERROR: The file is too big.")

    if st.button("**Silme**", disabled=st.session_state.disable_second_button):
        st.write("_Parola: 'gıcık'_")
        st.write("Bu parolayı Mocha'ya ilettiğinde o sana gerekli haberleri verecek.")
        st.image("resimler/milk-and-mocha-milk-mocha-bear.gif")
    
    
 #   st.markdown("_Bu durağa kadar geldiysen teşekkür ederim. Anılar kısmında elbette yaşanılan bütün anılar yok. Sadece küçük bir fragman diyebiliriz. Geçirilen her an özel her an tarifsiz duygu içeriyor. Dönüp bu zamanlara baktığımızda her şey çok kısa gibi, ama koca iki sene. Şimdi yapman gereken iki seçenek mevcut aşağıda. İlki var olan tüm anıları ve duyguları silecek. Sonrasında hiçbir şey olmayacak ve ikinci seçeneğe asla tıklanamayacak. Eğer ikinci seçeneği seçersen anılar silinmeyecek ve yeni bir pencere açılacak. Bu pencerede neler çıkacağını bu noktada bilemiyoruz. Yalnızca açıldığında görebileceksin. O yüzden kararını düşünerek vermelisin. Tıpkı şu an yaşadığımız hayat gibi bu da bir seçim. Kararlarımız bir sonraki adımların belirsizliğiyle devam eder. Onları açmadan nelerle karşılaşacağımızı bilemeyiz. Her neyi seçecek olursan seninle tanışmak benim başıma gelen en güzel şeydi Milk!_")
 #   if st.button("Tüm Anıları Sil"):
 #       st.error("Files can not deleted: Files are too big")

 #   if st.button("Anıları Silme"):
 #       st.write("_Parola: 'gıcık'_")
 #       st.write("Bu parolayı Mocha'ya ilettiğinde o sana gerekli haberleri verecek.")
